name: drag_container
description: Pull drawer effect with flutter, support click open and close, support drag open and close, support swipe gesture open and close
version: 2.0.0
homepage: https://github.com/zhaolongs/drag_container.git

environment:
  # sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=2.0.0"

  sdk: ">=2.14.0 <3.0.0"
  # flutter: ">=1.17.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


